config/routes.rb
Rails.application.routes.draw do
  resources :tokkens
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end
  post '/graphql', to: 'graphql#execute'

  resources :answers, except: %i[update edit]
  put '/answers/', to: 'answers#update'
  resources :comments
  resources :contentwebs do
    resources :pages
  end
  devise_for :users, :path => 'accounts'
  resources :users do
       resources :words
  end

  resources :tokkens

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :webhooks, only: [:create]

  scope controller: :home do
    get :about
  end
  scope controller: :static do
    get :help
    get :contact
    get :product
    get :dashboard
    get :admin_dashboard
  end
  scope controller: :admin do
    get :index
  end
  resources :notifications
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  has_many :notifications
end

app/models/appointement.rb
class Appointement < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :notifications
end

app/models/contact.rb
class Contact < ApplicationRecord
  extend FriendlyId
  friendly_id :place, use: :slugged
end

app/models/contentweb.rb
class Contentweb < ApplicationRecord
  belongs_to :user
  has_many :pages
end

app/models/facebookmodif.rb
class Facebookmodif < ApplicationRecord
  belongs_to :user
end

app/models/googlemodif.rb
class Googlemodif < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :answer
  belongs_to :comment
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :contentweb
  belongs_to :user
end

app/models/tokken.rb
class Tokken < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Pay::Billable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_one :contentweb, dependent: :destroy
  has_many :comments
  has_many :answers, through: :comment
  has_many :words
  has_many :facebookmodifs
  has_many :webmodifs
  has_many :googlemodifs
  has_many :appointements
  has_many :tokkens
  has_many :notifications
  has_many :pages

  pay_customer
end

app/models/webmodif.rb
class Webmodif < ApplicationRecord
  belongs_to :user
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/controllers/contentwebs_controller.rb
class ContentwebsController < ApplicationController
  before_action :set_contentweb, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /contentwebs or /contentwebs.json
  def index
    @user = current_user
    @contentwebs = Contentweb.all
  end

  # GET /contentwebs/1 or /contentwebs/1.json
  def show
    @user = current_user
    @contentweb = @user.contentweb
  end

  # GET /contentwebs/new
  def new
    @contentweb = Contentweb.new
  end

  # GET /contentwebs/1/edit
  def edit; end

  # POST /contentwebs or /contentwebs.json
  def create
    @contentweb = Contentweb.new(contentweb_params)

    respond_to do |format|
      if @contentweb.save
        format.html do
          redirect_to @contentweb,
                      notice: 'Contentweb was successfully created.'
        end
        format.json { render :show, status: :created, location: @contentweb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @contentweb.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /contentwebs/1 or /contentwebs/1.json
  def update
    respond_to do |format|
      if @contentweb.update(contentweb_params)
        format.html do
          redirect_to @contentweb,
                      notice: 'Contentweb was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @contentweb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @contentweb.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /contentwebs/1 or /contentwebs/1.json
  def destroy
    @contentweb.destroy
    respond_to do |format|
      format.html do
        redirect_to contentwebs_url,
                    notice: 'Contentweb was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contentweb
    @contentweb = Contentweb.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contentweb_params
    params
      .require(:contentweb)
      .permit(
        :header,
        :header2,
        :header3,
        :header4,
        :contentmain,
        :content2,
        :content3,
        :content4,
        :content5,
        :content6,
        :user_id,
        :nom_site,
        :titre_hero,
        :slogan,
        :descrp_title_1,
        :descrp_title_2,
        :descrp_title_3,
        :descrp_title_4,
        :descrp_sub_title_1,
        :descrp_sub_title_2,
        :descrp_sub_title_3,
        :descrp_sub_title_4,
        :descrp_text_1,
        :descrp_text_2,
        :descrp_text_3,
        :descrp_text_4,
        :header5,
        :header6,
        :sub_header1,
        :sub_header2,
        :sub_header3,
        :sub_header4,
        :sub_header5,
        :sub_header6
      )
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/contentwebs_helper.rb
module ContentwebsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def react_component(name, props = {})
    content_tag(
      :div,
      '',
      data: {
        react_component: {
          name: name,
          props: props
        }
      }
    )
  end
end

app/helpers/static_helper.rb
module StaticHelper
  def get_facebook
    # url="https://graph.facebook.com/v12.0/100425791706830?fields=fan_count&access_token="+user_tokken
    # return response= Faraday.get(url)
  end
end

app/helpers/tokkens_helper.rb
module TokkensHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/contentwebs/_blogcontent.html.erb
 <div class="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
      <div class="text-center mb-12">
        <h1 class="sm:text-3xl text-2xl font-bold title-font text-gray-900 mb-4">Notre blog</h1>
        <p class="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto text-gray-500s">
          Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo
          juice poutine, ramps microdosing banh mi pug.
        </p>
        <div class="flex mt-6 justify-center">
          <div class="w-16 h-1 rounded-full bg-blue-800 inline-flex"></div>
        </div>
      </div>
      <div class="grid gap-8 lg:grid-cols-3 sm:max-w-sm sm:mx-auto lg:max-w-full">
        <div class="overflow-hidden transition-shadow duration-300 bg-white rounded shadow-sm">
          <img
            src="https://images.pexels.com/photos/2408666/pexels-photo-2408666.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;w=500"
            class="object-cover w-full h-64"
            alt=""
          />
          <div class="p-5 border border-t-0">
            <p class="mb-3 text-xs font-semibold tracking-wide uppercase">
              <a
                href="/"
                class="transition-colors duration-200 text-blue-gray-900 hover:text-deep-purple-accent-700"
                aria-label="Category"
                title="Mode"
              >
                Mode
              </a>
              <span class="text-gray-600">— 28 Dec 2020</span>
            </p>
            <a
              href="/"
              aria-label="Category"
              title="Visit the East"
              class="inline-block mb-3 text-2xl font-bold leading-5 transition-colors duration-200 hover:text-deep-purple-accent-700"
            >
              Visit the East
            </a>
            <p class="mb-2 text-gray-700">
              Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni
              voluptatem doloremque.
            </p>
            <a
              href="/"
              aria-label=""
              class="inline-flex items-center font-semibold transition-colors duration-200 text-deep-purple-accent-400 hover:text-deep-purple-800"
            >
              Lire plus
            </a>
          </div>
        </div>
        <div class="overflow-hidden transition-shadow duration-300 bg-white rounded shadow-sm">
          <img
            src="https://images.pexels.com/photos/447592/pexels-photo-447592.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260"
            class="object-cover w-full h-64"
            alt=""
          />
          <div class="p-5 border border-t-0">
            <p class="mb-3 text-xs font-semibold tracking-wide uppercase">
              <a
                href="/"
                class="transition-colors duration-200 text-blue-gray-900 hover:text-deep-purple-accent-700"
                aria-label="Category"
                title="Mode"
              >
                Mode
              </a>
              <span class="text-gray-600">— 28 Dec 2020</span>
            </p>
            <a
              href="/"
              aria-label="Category"
              title="Simple is better"
              class="inline-block mb-3 text-2xl font-bold leading-5 transition-colors duration-200 hover:text-deep-purple-accent-700"
            >
              Simple is better
            </a>
            <p class="mb-2 text-gray-700">
              Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni
              voluptatem doloremque.
            </p>
            <a
              href="/"
              aria-label=""
              class="inline-flex items-center font-semibold transition-colors duration-200 text-deep-purple-accent-400 hover:text-deep-purple-800"
            >
              Lire plus
            </a>
          </div>
        </div>
        <div class="overflow-hidden transition-shadow duration-300 bg-white rounded shadow-sm">
          <img
            src="https://images.pexels.com/photos/139829/pexels-photo-139829.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260"
            class="object-cover w-full h-64"
            alt=""
          />
          <div class="p-5 border border-t-0">
            <p class="mb-3 text-xs font-semibold tracking-wide uppercase">
              <a
                href="/"
                class="transition-colors duration-200 text-blue-gray-900 hover:text-deep-purple-accent-700"
                aria-label="Category"
                title="Mode"
              >
                Mode
              </a>
              <span class="text-gray-600">— 28 Dec 2020</span>
            </p>
            <a
              href="/"
              aria-label="Category"
              title="Film It!"
              class="inline-block mb-3 text-2xl font-bold leading-5 transition-colors duration-200 hover:text-deep-purple-accent-700"
            >
              Film It!
            </a>
            <p class="mb-2 text-gray-700">
              Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni
              voluptatem doloremque.
            </p>
            <a
              href="/"
              aria-label=""
              class="inline-flex items-center font-semibold transition-colors duration-200 text-deep-purple-accent-400 hover:text-deep-purple-800"
            >
              Lire plus
            </a>
          </div>
        </div>
      </div>
    </div>

app/views/contentwebs/_controlcontent.html.erb
<div class="h-full  bg-gray-200 border-b-2 border-gray-40">
        <div class="grid grid-cols-12 gap-0">
            <div class="col-span-12 sm:col-span-12 md:col-span-12 lg:col-span-12 xxl:col-span-12 px-6 py-6">
                <!-- Start profile Card -->
                 <div class="bg-white rounded-xl p-4 shadow-xl mt-4">
                    <div class="flex flex-col justify-center items-center">
                       <img src="https://cdn3d.iconscout.com/3d/premium/thumb/upload-social-media-post-4291893-3569926.png" class="w-auto h-40 rounded-lg"/>
                        <p class="font-semibold text-xl mt-1">Construction du site</p>
                        <p class="font-semibold text-sm text-gray-400 text-center">Vous permets de créer, éditer, ajouter ou supprimer  <br> du contenu pour votre sitre vitrine</p>
                        
                        <div class="flex flex-row space-x-4">
                            <button class=" mt-4 bg-gray-600 hover:bg-gray-700 shadow-xl text-white font-bold py-2 px-4 rounded flex flex-inline">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path d="M8.445 14.832A1 1 0 0010 14v-2.798l5.445 3.63A1 1 0 0017 14V6a1 1 0 00-1.555-.832L10 8.798V6a1 1 0 00-1.555-.832l-6 4a1 1 0 000 1.664l6 4z" />
                                </svg>
                                <%= link_to 'Back', contentwebs_path %>   
                            </button>
                           
                            <button class=" mt-4 bg-pink-600 hover:bg-pink-700 shadow-xl text-white font-bold py-2 px-4 rounded" title="cliquer">
                                    <%= link_to 'Voir un aperçu', @contentweb %> 
                            </button>
                            <button class=" mt-4 bg-indigo-600 hover:bg-indigo-700 shadow-xl text-white font-bold py-2 px-4 rounded">
                                    <%= link_to 'Modifier', edit_contentweb_path(@contentweb) %>
                            </button> 
                            
                            <button class=" mt-4 bg-red-600 hover:bg-red-700 shadow-xl text-white font-bold py-2 px-4 rounded">
                                <%= link_to 'Effacez le contenu', @contentweb, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %>
                            </button>
                            <button class=" mt-4 bg-green-600 hover:bg-green-700 shadow-xl text-white font-bold py-2 px-4 rounded">
                                <%= link_to 'Créez Votre de nouvelles pages WEB', contentweb_pages_path(@contentweb) %>
                                <%if current_user.contentweb.nil?%>
                                    <%= link_to 'Créez Votre première page WEB', new_contentweb_path, class: 'text-5xl font-bold text-green-900' %>
                                <%end%>  
                            </button>
                        </div>
                         
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/contentwebs/_faqcontent.html.erb
 <section class="bg-coolGray-100 text-coolGray-800">
      <div class="container flex flex-col justify-center p-4 mx-auto md:p-8">
        <div class="text-center mb-12">
          <h1 class="sm:text-3xl text-2xl font-bold title-font text-gray-900 mb-4">FAQ</h1>
          <p class="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto text-gray-500s">
            Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub
            indxgo juice poutine, ramps microdosing banh mi pug.
          </p>
          <div class="flex mt-6 justify-center">
            <div class="w-16 h-1 rounded-full bg-blue-800 inline-flex"></div>
          </div>
        </div>
        <div class="flex flex-col divide-y sm:px-8 lg:px-12 xl:px-32 divide-coolGray-300">
          <details>
            <summary class="py-2 outline-none cursor-pointer focus:underline">
              Optio maiores eligendi molestiae totam dolores similique?
            </summary>
            <div class="px-4 pb-4">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde neque in fugiat magni,
                quas animi enim veritatis deleniti ex. Impedit.
              </p>
            </div>
          </details>
          <details>
            <summary class="py-2 outline-none cursor-pointer focus:underline">
              Modi dolorem veritatis culpa quos consequuntur beatae itaque excepturi perspiciatis?
            </summary>
            <div class="px-4 pb-4">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Est aspernatur quae, eos
                explicabo odit minima libero veniam similique quibusdam doloribus facilis ipsa
                accusantium vel maiores corrupti! Libero voluptate a doloribus?
              </p>
            </div>
          </details>
          <details>
            <summary class="py-2 outline-none cursor-pointer focus:underline">
              Magni reprehenderit possimus debitis?
            </summary>
            <div class="px-4 pb-4 space-y-2">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut voluptates aspernatur
                dolores in consequatur doloremque inventore reprehenderit, consequuntur perspiciatis
                architecto.
              </p>
              <p>
                Sed consectetur quod tenetur! Voluptatibus culpa incidunt veritatis velit quasi
                cupiditate unde eaque! Iure, voluptatibus autem eaque unde possimus quae.
              </p>
            </div>
          </details>
        </div>
      </div>
    </section>

app/views/contentwebs/_featurescontent.html.erb
<section class="text-gray-600 body-font">
      <div class="text-center mb-20 mt-8">
        <h1 class="sm:text-3xl text-2xl font-bold title-font text-gray-900 mb-4">
          Votre savoir faire
        </h1>
        <p class="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto text-gray-500s">
          Quels sont les atouts/connaissances/services de votre entreprise
        </p>
        <div class="flex mt-6 justify-center">
          <div class="w-16 h-1 rounded-full bg-blue-800 inline-flex"></div>
        </div>
      </div>
      <div class="container px-5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full mb-10 lg:mb-0 rounded-lg overflow-hidden">
          <img
            alt="feature"
            class="object-cover object-center h-full w-full"
            src="https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260"
          />
        </div>
        <div class="flex flex-col flex-wrap lg:py-6 -mb-10 lg:w-1/2 lg:pl-12 lg:text-left text-center">
          <div class="flex flex-col mb-10 lg:items-start items-center">
            <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-indigo-100 text-blue-800 mb-5">
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-6 h-6"
                viewBox="0 0 24 24"
              >
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Shooting Stars</h2>
              <p class="leading-relaxed text-base">
                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub
                indxgo juice poutine.
              </p>
              <a class="mt-3 text-blue-800 inline-flex items-center">
                En savoir plus
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
          <div class="flex flex-col mb-10 lg:items-start items-center">
            <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-indigo-100 text-blue-800 mb-5">
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-6 h-6"
                viewBox="0 0 24 24"
              >
                <circle cx="6" cy="6" r="3"></circle>
                <circle cx="6" cy="18" r="3"></circle>
                <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">The Catalyzer</h2>
              <p class="leading-relaxed text-base">
                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub
                indxgo juice poutine.
              </p>
              <a class="mt-3 text-blue-800 inline-flex items-center">
                En savoir plus
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
          <div class="flex flex-col mb-10 lg:items-start items-center">
            <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-indigo-100 text-blue-800 mb-5">
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-6 h-6"
                viewBox="0 0 24 24"
              >
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Neptune</h2>
              <p class="leading-relaxed text-base">
                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub
                indxgo juice poutine.
              </p>
              <a class="mt-3 text-blue-800 inline-flex items-center">
                En savoir plus
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
          <div class="flex flex-col mb-10 lg:items-start items-center">
            <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-indigo-100 text-blue-800 mb-5">
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-6 h-6"
                viewBox="0 0 24 24"
              >
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Neptune</h2>
              <p class="leading-relaxed text-base">
                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub
                indxgo juice poutine.
              </p>
              <a class="mt-3 text-blue-800 inline-flex items-center">
                En savoir plus
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </div>
</section>

app/views/contentwebs/edit.html.erb
<%= render 'contentwebs/controlcontent'%>
<%= render 'form', contentweb: @contentweb %>

app/views/contentwebs/index.html.erb
<p id="notice"><%= notice %></p>
<!--Navbar-->

<%= render 'contentwebs/navbarcontent'%>

<!--Hero-->


<%= render 'contentwebs/herocontent'%>
<%= render 'contentwebs/featurescontent'%>
<%= render 'contentwebs/productcontent'%>
<%= render 'contentwebs/stepscontent'%>
<%= render 'contentwebs/teamcontent'%>
<%= render 'contentwebs/blogcontent'%>
<%= render 'contentwebs/faqcontent'%>
<!--Première description-->



<!--Blogs-->

app/views/contentwebs/new.html.erb
<h1 class="text-4xl font-bold text-gray-50 bg-red-600 px-4 py-2 ">Remplissez les parties vides avec les consignes suggerées </h1>

<%= render 'form', contentweb: @contentweb %>

<%= link_to 'Back', contentwebs_path %>



<div>Header 1 
<div>Veuillez remplir ici la partie Header 1 qui va donner un titre </div>

</div>