config/routes.rb
Rails.application.routes.draw do
  resources :tokkens
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end
  post '/graphql', to: 'graphql#execute'

  resources :answers, except: %i[update edit]
  put '/answers/', to: 'answers#update'
  resources :comments
  resources :contentwebs do
    resources :pages
  end
  devise_for :users, :path => 'accounts'
  resources :users do
       resources :words
  end

  resources :tokkens

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :webhooks, only: [:create]

  scope controller: :home do
    get :about
  end
  scope controller: :static do
    get :help
    get :contact
    get :product
    get :dashboard
    get :admin_dashboard
  end
  scope controller: :admin do
    get :index
  end
  resources :notifications
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  has_many :notifications
end

app/models/appointement.rb
class Appointement < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :notifications
end

app/models/contact.rb
class Contact < ApplicationRecord
  extend FriendlyId
  friendly_id :place, use: :slugged
end

app/models/contentweb.rb
class Contentweb < ApplicationRecord
  belongs_to :user
  has_many :pages
end

app/models/facebookmodif.rb
class Facebookmodif < ApplicationRecord
  belongs_to :user
end

app/models/googlemodif.rb
class Googlemodif < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :answer
  belongs_to :comment
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :contentweb
  belongs_to :user
end

app/models/tokken.rb
class Tokken < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Pay::Billable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_one :contentweb, dependent: :destroy
  has_many :comments
  has_many :answers, through: :comment
  has_many :words
  has_many :facebookmodifs
  has_many :webmodifs
  has_many :googlemodifs
  has_many :appointements
  has_many :tokkens
  has_many :notifications
  has_many :pages

  pay_customer
end

app/models/webmodif.rb
class Webmodif < ApplicationRecord
  belongs_to :user
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Stripe.api_key=Rails.application.credentials.stripe[:secret_key]
  def index
    @page_title = 'Accueil'
    @page_description = "Bienvenue sur le site de la communauté de l'informatique"
    @page_keywords = 'informatique, communauté, site, communauté informatique, site communauté, site communauté informatique'

    # @customer_list = Stripe::Customer.list.data
  end

  def create
    @user = current_user
    @user.tokken = params[:tokken]
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def react_component(name, props = {})
    content_tag(
      :div,
      '',
      data: {
        react_component: {
          name: name,
          props: props
        }
      }
    )
  end
end

app/helpers/static_helper.rb
module StaticHelper
  def get_facebook
    # url="https://graph.facebook.com/v12.0/100425791706830?fields=fan_count&access_token="+user_tokken
    # return response= Faraday.get(url)
  end
end

app/helpers/tokkens_helper.rb
module TokkensHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/home/_bullshit.html.erb
<div class=" w-full h-96 ">

          


          <div class="bg-gradient-to-r animate-pulse duration-500  from-purple-400 via-pink-500 to-red-500 w-full h-96" style="clip-path: circle(80% at 15% 4%)">
          </div>
          <div class="absolute  top-32">
                  <%if current_user%>
                      <h1 class="text-3xl bg-blue-500 text-white text-center py-2 px-4 font-bold  ">Welcome <%= current_user.email%></h1>
                  <%else%>
                      <h1 class="  pl-4 pr-20 py-4 text-4xl text-left z-20 font-extrabold text-gray-800 mb-10">Votre plateforme d'acquisition de <br>prospect ! </h1>
                      <div class="flex">
                          <a href='https://buy.stripe.com/test_dR65m37kd5uK0DK289' class="bg-yellow-400 ml-5  rounded-lg font-extrabold text-xl px-4 py-2 text-gray-100">Commencer </a>
                          <button class="border-2 bg-yellow-100 border-yellow-400 ml-5 mr-10 rounded-lg font-extrabold text-lg px-4 py-2 text-gray-400">Plus de détails</button>
                      
                      </div>
                   <%end%>

           </div>
         
</div>

<div class="my-5 ml-28"><%= image_tag "Network _Isometric.svg", height: 200 %></div>
<%= link_to 'Dashboard', dashboard_path, class: " text-center text-5xl bg-red-500 text-gray-50 font-bold" %>


<%# First Part explanation of who we are%>
<section class=" mb-20  py-4">
<div class="px-10">
   <h2 class="  text-4xl text-left z-20 font-extrabold text-gray-800 mb-10">Une phrase forte qui définit notre produit, un truc qui tape !</h2>

   
   <p class="text-xl text-gray-600 ">
      Un paragraphe qui décrit ce que nous sommes avec des mots clès très pertinenents. Chaque phrases qui décrit une partie de <a href ="#" class="text-pink-700" >notre produit est un lien.</a><br>
      Et faire becuoup de ce genre de phrase avec à <a href ="#" class="text-pink-700" >chaque fois des liens </a>
   </p >
   <p class= "text-xl text-gray-600 mb-16">
       Un paragraphe qui décrit ce que nous sommes avec des mots clès très pertinenents. Chaque phrases qui décrit une partie de <a href ="#" class="text-pink-700" >notre produit est un lien.</a><br>
      Et faire becuoup de ce genre de phrase avec à <a href ="#" class="text-pink-700" >chaque fois des liens </a>
      
   </p>
   <a href="#" class="bg-pink-400 py-2 px-4 rounded-lg  text-gray-100 font-semibold">Connaitre les détails de notre manière de proceder </a>
</div>

  

</section>


<%=render "contact" %>
Nizar Christian M'rad

app/views/home/_contact.html.erb
<form action="https://formsubmit.co/contact@otos-lab.fr " method="POST"class="w-full mx-auto max-w-3xl bg-white shadow p-8 text-gray-700 ">


    <h2 class="w-full my-2 text-3xl font-bold leading-tight ">Contact form</h2>
    <!-- name field -->
    <div class="flex flex-wrap mb-6">
        <div class="relative w-full appearance-none label-floating">
            <input class="tracking-wide py-2 px-4 mb-3 leading-relaxed appearance-none block w-full bg-gray-200 border border-gray-200 rounded focus:outline-none focus:bg-white focus:border-gray-500"
            name="name" type="text" placeholder="Votre nom">
            <label for="name" class="absolute tracking-wide py-2 px-4 mb-4 opacity-0 leading-tight block top-0 left-0 cursor-text">
                Votre Nom
            </label>
        </div>
    </div>
    <!-- email field -->
    <div class="flex flex-wrap mb-6">
        <div class="relative w-full appearance-none label-floating">
            <input class="tracking-wide py-2 px-4 mb-3 leading-relaxed appearance-none block w-full bg-gray-200 border border-gray-200 rounded focus:outline-none focus:bg-white focus:border-gray-500"
             name="email" type="email" placeholder="Votre Mail (champs obligatoire)"required>
            <label for="name" class="absolute tracking-wide py-2 px-4 mb-4 opacity-0 leading-tight block top-0 left-0 cursor-text">
                Vore Mail
            </label>
        </div>
    </div>
    <!-- Message field -->
    <div class="flex flex-wrap mb-6">
        <div class="relative w-full appearance-none label-floating">
            <textarea class="autoexpand tracking-wide py-2 px-4 mb-3 leading-relaxed appearance-none block w-full bg-gray-200 border border-gray-200 rounded focus:outline-none focus:bg-white focus:border-gray-500"
                type="text" placeholder="Message..." name="message"></textarea>
                <label for="message" class="absolute tracking-wide py-2 px-4 mb-4 opacity-0 leading-tight block top-0 left-0 cursor-text">Message...
            </label>
        </div>
    </div>
    <input type="hidden" name="_next" value="http://localhost:3000/">
    <input type="hidden" name="_subject" value="LeadCollector Contact Message">

    <div class="">
        <button class="w-full shadow bg-teal-400 hover:bg-teal-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded"
            type="submit">
            Send
        </button>

    </div>
</form>

app/views/home/_explanations.html.erb
<div class='w-full primary lg:block h-full'>
<div class="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
  <div class="flex flex-col w-full mb-6 lg:justify-between lg:flex-row md:mb-8">
    <div class=" mb-10 md:mx-auto sm:text-center  md:mb-12 text-center">
        <h2 class=" inline-block max-w-lg mb-6 font-sans text-3xl font-bold leading-none tracking-tight  sm:text-4xl md:mx-auto md:text-center">
          
          <span class="text-gray-50"> Générer de nouveaux clients n'a jamais été aussi simple</span>
        </h2>
      </div>
    
  </div>
  <div class="grid gap-8 row-gap-5 mb-8 lg:grid-cols-3 lg:row-gap-8">
    <div>
      
     <%= image_tag "choose-plan.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>

      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>1.</span> Choix de l'abonnement
      </p>
      <p class="text-gray-50">
        Prenez l'abonnement qui répond aux besoins de votre entreprise.
      </p>
    </div>
    <div>
      <%= image_tag "team-meeting.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>2.</span> Prise de contact
      </p>
      <p class="text-gray-50">
        Un développeur qui sera votre référent durant la mise en place du site internet va prendre contact avec vous.
      </p>
    </div>
    <div>
      <%= image_tag "data-processing.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>3.</span> Transfert de données
      </p>
      <p class="text-gray-50">
        Grâce à notre plateforme internet connecter vous pour nous transférer les données nécéssaires à la création de votre site (images , textes etc.)
      </p>
    </div>
    <div>
      <%= image_tag "web-production.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>4.</span> Création du site web
      </p>
      <p class="text-gray-50">
        Une fois les données transmises à notre entreprise, nos équipes de développeurs peuvent passer à la phase de conception du site internet.
      </p>
    </div>
    <div>
      <%= image_tag "communication.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>5.</span> Derniers réglages
      </p>
      <p class="text-gray-50">
        Une première version de votre site internet vous est transmise. Vous pourrez nous donner votre retour et les derniers changements à effectuer.
      </p>
    </div>
    <div>
      <%= image_tag "visibility.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>6.</span> Votre site est en ligne
      </p>
      <p class="text-gray-50">
        Votre site vitrine est mis en ligne, votre entreprise entre dans la sphère internet pour mettre votre activité en lumière !
      </p>
    </div>
    <div>
      <%= image_tag "seo.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>7.</span> Optimisation SEO
      </p>
      <p class="text-gray-50">
        Le site fourni est optimisé SE0 et notre équipe de journaliste SEO prennent le relais afin d'écrire hébdomairement le nombre d'articles correspondant à votre abonnement.
      </p>
    </div>
    <div>
      <%= image_tag "social-media.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>8.</span> Gestion réseaux sociaux
      </p>
      <p class="text-gray-50">
        Notre équipe de Community Manager prennent le relais pour la gestion des réseaux sociaux (Instagram, Facebook)
      </p>
    </div>
    <div>
      <%= image_tag "results.svg", :class => 'object-contain md:object-cover objet-center w-full h-56 mb-6 rounded shadow-lg md:h-64 xl:h-80 bg-black px-2' %>
      <p class="mb-2 text-xl font-bold leading-none sm:text-2xl text-gray-50">
        <span class='text-gray-900'>9.</span> Découvrez les resultats
      </p>
      <p class="text-gray-50">
        L'ensemble de ses mesures vont vous permettre de gagner en visibilé, de générer du traffic sur votre site et générer de nouveaux prospects (Installer vous comfortablement et laisser vous guidez par nos équipes).
      </p>
    </div>
  </div>
  
</div>
</div>

app/views/home/_hero.html.erb
<div class="relative">
   
      <svg
        class="absolute inset-0 object-cover"
        id="my-svg"
        version="1"
        baseProfile="full"
        
        viewBox="0 0 1440 720"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect class='w-full h-full' fill="#000"></rect>
        <defs>
          <linearGradient id="linear-gradient" x1="0" x2="1" y1="0" y2="1">
            <stop offset="0%" stop-color="#ca128f90"></stop>
            <stop offset="100%" stop-color="#2a46c090"></stop>
          </linearGradient>
        </defs>
        <path
          transform="scale(1, 1)"
          d="M 0,720 V 0,420 C 129.07142857142858,474.9642857142857 258.14285714285717,529.9285714285714 367,552 C 475.85714285714283,574.0714285714286 564.4999999999999,563.25 694,498 C 823.5000000000001,432.75 993.8571428571429,313.0714285714286 1125,291 C 1256.142857142857,268.9285714285714 1348.0714285714284,344.46428571428567 1440,420 C 1440,420 1440,720 1440,720 Z"
          stroke="none"
          stroke-width="0"
          fill="url(#linear-gradient)"
          class="transition-all duration-300 ease-in-out delay-150"
        ></path>
        <defs>
          <linearGradient id="linear-gradient" x1="0" x2="1" y1="0" y2="1">
            <stop offset="0%" stop-color="#ca128fff"></stop>
            <stop offset="100%" stop-color="#2a46c0ff"></stop>
          </linearGradient>
        </defs>
        <path
          transform="scale(1, 1)"
          d="M 0,720 V 0,630 C 116.03571428571428,682.3214285714286 232.07142857142856,734.6428571428571 357,695 C 481.92857142857144,655.3571428571429 615.75,523.75 743,505 C 870.25,486.25 990.9285714285716,580.3571428571429 1106,620 C 1221.0714285714284,659.6428571428571 1330.5357142857142,644.8214285714286 1440,630 C 1440,630 1440,720 1440,720 Z"
          stroke="none"
          stroke-width="0"
          fill="url(#linear-gradient)"
          class="transition-all duration-300 ease-in-out delay-150"
        ></path>
      </svg>
      <div class="relative bg-opacity-75">
       

        <div class="relative px-4 py-16 mx-auto overflow-hidden sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
          <div class="flex flex-col items-center justify-between xl:flex-row">
            <div class="max-w-xl  xl:mb-0 xl:pr-16 xl:w-7/12">
            <%if current_user%>
              <h2 class="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-white sm:text-4xl sm:leading-none">
                Bienvenue <br class="hidden md:block" />
                <%= current_user.email%>
              </h2>
              <p class="max-w-xl mb-4 text-base text-gray-200 md:text-lg">
                Vous avez des questions ? des modifications à faire ? 
              </p>
              <a
                href="/"
                aria-label=""
                class="inline-flex items-center font-semibold tracking-wider transition-colors duration-200 text-white hover:text-pink-600"
              >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2 animate-bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 9l3 3m0 0l-3 3m3-3H8m13 0a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
                Tableau de board  
              </a>
              <%else%>
              <h2 class="max-w-lg mb-6 font-sans text-xl font-bold tracking-tight text-white sm:text-4xl sm:leading-none">
                Bienvenue chez Lead Collector <br class="hidden md:block" />
                l'offre digitale "All-inclusive" qui va révolutionner votre entreprise !
              </h2>
              <p class="invisible md:visible max-w-xl mb-4 text-base text-gray-200 md:text-lg">
                Choississez l'abonnement qui vous convient pour commencer votre partenariat avec notre entreprise et obtennez un site vitrine à la fin de votre contrat !
              </p>
              
                <%= link_to 'En savoir plus', product_path, class: "inline-flex items-center font-semibold tracking-wider transition-colors duration-200 text-white hover:text-pink-600 invisible md:visible" %>
                <svg class="invisible md:visible inline-block w-3 ml-2 text-gray-50" fill="currentColor" viewBox="0 0 12 12">
                  <path d="M9.707,5.293l-5-5A1,1,0,0,0,3.293,1.707L7.586,6,3.293,10.293a1,1,0,1,0,1.414,1.414l5-5A1,1,0,0,0,9.707,5.293Z" />
                </svg>
              </a>
              <% end %>
            </div>
            <%if current_user%>
            <div class="max-w-xl xl:px-8 xl:w-5/12 mb-60">
              <div class="bg-white rounded shadow-2xl p-7 sm:p-10">
                <h3 class="mt-6 text-xl font-semibold sm:text-center sm:mb-6 sm:text-2xl">
                  Des questions ? 
                </h3>
              
                <%=form_with( url: comments_path, method: :post)  do |form| %>
                <div class="mt-12 mb-12 xl:w-96">
                  <%=form.label :Message, class: 'form-label inline-block mb-2 text-gray-700'%>
             
                <%= form.text_area :body, class:"
                    form-control
                    block 
                    w-full
                    px-3
                    py-1.5
                    text-base
                    font-normal
                    text-gray-700
                    bg-white bg-clip-padding
                    border border-solid border-gray-300
                    rounded
                    transition
                    ease-in-out
                    m-0
                    focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
                  ",
                  id: "exampleFormControlTextarea1",
                  rows: 5,
                  placeholder: 'Votre message'%>
                  
               </div>
               <%= form.hidden_field :user_id, value: current_user.id%>
                 <div class="mt-8 mb-2 sm:mb-4">
                        <%= form.submit "Envoyez", class: "inline-flex cursor-pointer items-center justify-center w-full h-12 px-6 font-medium tracking-wide text-white transition duration-200 rounded shadow-md bg-pink-600 hover:bg-pink-700 focus:shadow-outline focus:outline-none" %>
                          
                       
                         
                       
                  </div>

                <%end%>
                  
                 
   
                  <p class="text-xs text-gray-600 sm:text-sm">
                    Nous respectons votre vie privée. Mentions légales
                  </p>
               
              </div>
            </div>
            <%else%>
            <div class="max-w-xl xl:px-8 xl:w-5/12">
              <div class="bg-white rounded shadow-2xl p-7 sm:p-10">
                <h3 class="mb-4 text-xl font-semibold sm:text-center sm:mb-6 sm:text-2xl">
                  Des questions ? 
                </h3>
                <form action="https://formsubmit.co/contact@otos-lab.fr " method="POST">
                  
                  <div class="mb-1 sm:mb-2">
                    <label htmlFor="lastName" class="inline-block mb-1 font-medium">
                      Nom
                    </label>
                    <input
                      placeholder="Doe"
                      required
                      type="text"
                      class="flex-grow w-full h-12 px-4 mb-2 transition duration-200 bg-white border border-gray-300 rounded shadow-sm appearance-none focus:border-deep-purple-accent-400 focus:outline-none focus:shadow-outline"
                      id="lastName"
                      name="lastName"
                    />
                  </div>
                  <div class="mb-1 sm:mb-2">
                    <label htmlFor="email" class="inline-block mb-1 font-medium">
                      E-mail
                    </label>
                    <input
                      placeholder="john.doe@example.org"
                      required
                      type="text"
                      class="flex-grow w-full h-12 px-4 mb-2 transition duration-200 bg-white border border-gray-300 rounded shadow-sm appearance-none focus:border-deep-purple-accent-400 focus:outline-none focus:shadow-outline"
                      id="email"
                      name="email"
                    />
                  </div>
                  <div class="mb-3 xl:w-96">
                    <label for="exampleFormControlTextarea1" class="form-label inline-block mb-2 text-gray-700"
                      >Message</label
                    >
                    <textarea
                      class="
                        form-control
                        block
                        w-full
                        px-3
                        py-1.5
                        text-base
                        font-normal
                        text-gray-700
                        bg-white bg-clip-padding
                        border border-solid border-gray-300
                        rounded
                        transition
                        ease-in-out
                        m-0
                        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
                      "
                      id="exampleFormControlTextarea1"
                      rows="3"
                      placeholder="Votre message"
                    ></textarea>
                  </div>
                  <div class="mt-4 mb-2 sm:mb-4">
                    <button
                      type="submit"
                      class="inline-flex items-center justify-center w-full h-12 px-6 font-medium tracking-wide text-white transition duration-200 rounded shadow-md bg-pink-600 hover:bg-pink-700 focus:shadow-outline focus:outline-none"
                    >
                      Envoyez
                    </button>
                  </div>
                  <p class="text-xs text-gray-600 sm:text-sm">
                    Nous respectons votre vie privée. Mentions légales
                  </p>
                </form>
              </div>
            </div>
            <% end %>
          </div>
          
          
        </div>
      </div>
    </div>

app/views/home/index.html.erb
<%= render 'home/hero'%>
<%= render 'home/features' %>
<%= render 'home/prices' %>
<%= render 'home/process' %>
<%= render 'home/teams' %>