config/routes.rb
Rails.application.routes.draw do
  resources :tokkens
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end
  post '/graphql', to: 'graphql#execute'

  resources :answers, except: %i[update edit]
  put '/answers/', to: 'answers#update'
  resources :comments
  resources :contentwebs do
    resources :pages
  end
  devise_for :users, :path => 'accounts'
  resources :users do
       resources :words
  end

  resources :tokkens

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :webhooks, only: [:create]

  scope controller: :home do
    get :about
  end
  scope controller: :static do
    get :help
    get :contact
    get :product
    get :dashboard
    get :admin_dashboard
  end
  scope controller: :admin do
    get :index
  end
  resources :notifications
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  has_many :notifications
end

app/models/appointement.rb
class Appointement < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :notifications
end

app/models/contact.rb
class Contact < ApplicationRecord
  extend FriendlyId
  friendly_id :place, use: :slugged
end

app/models/contentweb.rb
class Contentweb < ApplicationRecord
  belongs_to :user
  has_many :pages
end

app/models/facebookmodif.rb
class Facebookmodif < ApplicationRecord
  belongs_to :user
end

app/models/googlemodif.rb
class Googlemodif < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :answer
  belongs_to :comment
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :contentweb
  belongs_to :user
end

app/models/tokken.rb
class Tokken < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Pay::Billable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_one :contentweb, dependent: :destroy
  has_many :comments
  has_many :answers, through: :comment
  has_many :words
  has_many :facebookmodifs
  has_many :webmodifs
  has_many :googlemodifs
  has_many :appointements
  has_many :tokkens
  has_many :notifications
  has_many :pages

  pay_customer
end

app/models/webmodif.rb
class Webmodif < ApplicationRecord
  belongs_to :user
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/controllers/tokkens_controller.rb
class TokkensController < ApplicationController
  before_action :set_tokken, only: %i[show edit update destroy]

  # GET /tokkens or /tokkens.json
  def index
    @tokkens = Tokken.all
  end

  # GET /tokkens/1 or /tokkens/1.json
  def show; end

  # GET /tokkens/new
  def new
    @tokken = Tokken.new
  end

  # GET /tokkens/1/edit
  def edit; end

  # POST /tokkens or /tokkens.json
  def create
    @tokken = Tokken.new(tokken_params)

    respond_to do |format|
      if @tokken.save
        format.html do
          redirect_to @tokken, notice: 'Tokken was successfully created.'
        end
        format.json { render :show, status: :created, location: @tokken }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @tokken.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /tokkens/1 or /tokkens/1.json
  def update
    respond_to do |format|
      if @tokken.update(tokken_params)
        format.html do
          redirect_to @tokken, notice: 'Tokken was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @tokken }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @tokken.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /tokkens/1 or /tokkens/1.json
  def destroy
    @tokken.destroy
    respond_to do |format|
      format.html do
        redirect_to tokkens_url, notice: 'Tokken was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tokken
    @tokken = Tokken.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tokken_params
    params.require(:tokken).permit(:fbTokken, :gTokken, :user_id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def react_component(name, props = {})
    content_tag(
      :div,
      '',
      data: {
        react_component: {
          name: name,
          props: props
        }
      }
    )
  end
end

app/helpers/static_helper.rb
module StaticHelper
  def get_facebook
    # url="https://graph.facebook.com/v12.0/100425791706830?fields=fan_count&access_token="+user_tokken
    # return response= Faraday.get(url)
  end
end

app/helpers/tokkens_helper.rb
module TokkensHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/tokkens/_form.html.erb
<%= form_with(model: tokken) do |form| %>
  <% if tokken.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tokken.errors.count, "error") %> prohibited this tokken from being saved:</h2>

      <ul>
        <% tokken.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fbTokken %>
    <%= form.text_area :fbTokken %>
  </div>

  <div class="field">
    <%= form.label :gTokken %>
    <%= form.text_area :gTokken %>
  </div>

    <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tokkens/edit.html.erb
<h1>Editing Tokken</h1>

<%= render 'form', tokken: @tokken %>

<%= link_to 'Show', @tokken %> |
<%= link_to 'Back', tokkens_path %>

app/views/tokkens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tokkens</h1>

<table>
  <thead>
    <tr>
      <th class="bg-indigo-900 text-xl font-bold text-gray-50">Fbtokken</th>
      <th class="bg-indigo-900 text-xl font-bold text-gray-50">Gtokken</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokkens.each do |tokken| %>
      <tr>
        <td><%= tokken.fbTokken %></td>
        <td><%= tokken.gTokken %></td>
        <td><%= link_to 'Show', tokken %></td>
        <td><%= link_to 'Edit', edit_tokken_path(tokken) %></td>
        <td><%= link_to 'Destroy', tokken, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tokken', new_tokken_path %>

app/views/tokkens/new.html.erb
<h1>New Tokken</h1>

<%= render 'form', tokken: @tokken %>

<%= link_to 'Back', tokkens_path %>

app/views/tokkens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fbtokken:</strong>
  <%= @tokken.fbTokken %>
</p>

<p>
  <strong>Gtokken:</strong>
  <%= @tokken.gTokken %>
</p>

<%= link_to 'Edit', edit_tokken_path(@tokken) %> |
<%= link_to 'Back', tokkens_path %>